In [21]:
import numpy as np
arr1 = np.array([1,4,2,5,3])#creating numpy array
print(arr1)
arr2 = np.array([1,2,3,4], dtype = float) #explicitly mentioning the data type of resulting array
print(arr2)
arr3 = np.array([list(range(i, i+3)) for i in [2,4,6]])#creating 2d arrays
print(arr3)

[1 4 2 5 3]
[1. 2. 3. 4.]
[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [25]:
import numpy as np
arr0 = np.zeros(10, dtype = int)
print(arr0)
arr1 = np.ones((3,5), dtype = float)

print(arr1)
arr_of_choice = np.full((3,5), 3.14)
print(arr_of_choice)
arr_seq = np.arange(0, 20, 2)
print(arr_seq)
arr_random1 = np.random.random((3,3))
print(arr_random1)
arr_random2 = np.random.randint(0,10,(3,3))
print(arr_random2)
arr_identity = np.eye(3)
arr_empty = np.empty(3)
print(arr_empty)

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[ 0  2  4  6  8 10 12 14 16 18]
[[0.81216873 0.47997717 0.3927848 ]
 [0.83607876 0.33739616 0.64817187]
 [0.36824154 0.95715516 0.14035078]]
[[0 2 3]
 [8 1 3]
 [3 3 7]]
[3. 2. 1.]


In [27]:
#Accessing Numpy arrays
np.random.seed(0)
x1 = np.random.randint(4, 10, size = 6)
print(x1)
print(x1[-1])
x2 = np.random.randint(10, size =(3,4))
print(x2)
print(x2[2,-1])

[8 9 4 7 7 7]
7
[[7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
6


In [29]:
#Slicing in numpy arrays
np.random.seed(3)
x = np.arange(10)
print(x[5:], x[:5], x[5::-2])
x2 = np.random.randint(10, size =(3,4))
print(x2[:3, :2],x2[:3, ::2]) #2 rows, 3 cols  and all rows, alternate cols
print(x2[::-1, ::-1]) #reversing 2d array
print(x2[0]) #accessing 1st row
#can also be written as x2[0, :]
print(x2[:, 0]) #accessing 1st column

#numpy slices are views not a copy like lists in python
x2_sub = x2[:2, :2]
print(x2_sub)
x2[0,0] = 99
print(x2)
 #using .copy() to create shallow copies
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy[0, 0] = 55
print(x2)

[5 6 7 8 9] [0 1 2 3 4] [5 3 1]
[[8 9]
 [8 0]
 [9 9]] [[8 3]
 [8 5]
 [9 5]]
[[7 5 9 9]
 [3 5 0 8]
 [8 3 9 8]]
[8 9 3 8]
[8 8 9]
[[8 9]
 [8 0]]
[[99  9  3  8]
 [ 8  0  5  3]
 [ 9  9  5  7]]
[[99  9  3  8]
 [ 8  0  5  3]
 [ 9  9  5  7]]


In [31]:
#reshaping of arrays
# x = np.arange(1,10).reshape(3,3)
# print(x)

#concatenation of 1d arrays
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.concatenate([x,y])
z = np.concatenate([x,y,z])
print(z)
#concatenation of 2d arrays
grid = np.array([[1,2,3],[4,5,6]])
p = np.concatenate([grid, grid], axis = 0)
q = np.concatenate([grid,grid], axis = 1)
print(p)
print(q)
print(z)
grid = np.array([[9,8,7],[6,5,4]])
a = np.vstack([x,grid])
print(a)
b = np.array([[99],[99]])
b = np.hstack([grid,b])
print(b)

[1 2 3 3 2 1 1 2 3 3 2 1]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[1 2 3 3 2 1 1 2 3 3 2 1]
[[1 2 3]
 [9 8 7]
 [6 5 4]]
[[ 9  8  7 99]
 [ 6  5  4 99]]


In [33]:
#splitting of arrays
#splitting of arrays
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)
grid = np.arange(16).reshape(4,4)
upper, lower = np.vsplit(grid, [2])
print(upper,lower)
left, right = np.hsplit(grid, [2])
print(left, right)

[1 2 3] [99 99] [3 2 1]
[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [35]:
# Array Arithmetic

x = np.arange(4)
print(-x, x + 5, x - 2, x * 2, x / 2, x // 2, x ** 0.5, x % 2)
print(-(0.5 * x + 1) ** 2)
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

[ 0 -1 -2 -3] [5 6 7 8] [-2 -1  0  1] [0 2 4 6] [0.  0.5 1.  1.5] [0 0 1 1] [0.         1.         1.41421356 1.73205081] [0 1 0 1]
[-1.   -2.25 -4.   -6.25]
[2 1 0 1 2]


In [92]:
#trigonometric, logarthmic and exponential functions
theta = np.linspace(0,np.pi,3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))
x = [-1, 0, 1]
print(x)
print( np.arcsin(x))
print( np.arccos(x))
print( np.arctan(x))
x = [1,2,3]
print(np.exp(x))
print(np.exp2(x))
print(np.log2(x))
print(np.log10(x))
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))
print("3^x   =", np.power(3, x))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]
[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[0.        1.        1.5849625]
[0.         0.30103    0.47712125]
exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]
3^x   = [1.         1.00109922 1.01104669 1.11612317]


In [104]:
#For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. Rather than creating a temporary array, this can be used to write computation results directly to the memory location where you'd like them to be
x = np.arange(5)
y = np.empty(5)
# print(x,y)
np.multiply(x, 10, y)
print(y)
y = np.zeros(10)
np.power(2,x, y[::2])
print(y)

[ 0. 10. 20. 30. 40.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [110]:
#aggregates like reduce, accumulate, outer
x = np.arange(1,6)
print(np.add.reduce(x))
print(np.multiply.reduce(x))
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))
print(np.multiply.outer(x,x))

15
120
[ 1  3  6 10 15]
[  1   2   6  24 120]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [120]:
#Aggregations
np.random.seed(100)
#numpy aggregates are faster than python's built in functions
L=np.random.random(100)
print(np.sum(L))
# %timeit sum(L)
# %timeit sum(L)

big_array = np.random.random(10000)
print(np.max(big_array))
print(np.min(big_array))

#multi-dimensional aggregates
m = np.random.random((3,4))
print(m)
print(np.max(m))
print(np.max(m, axis = 0))
print(np.min(m, axis = 1))


47.23667917192546
0.9999778452090398
1.4618569125435243e-05
[[0.78079815 0.0631284  0.43856358 0.32974972]
 [0.23039523 0.3155974  0.38551725 0.33281114]
 [0.87458746 0.7314638  0.99504376 0.84022477]]
0.9950437570658559
[0.87458746 0.7314638  0.99504376 0.84022477]
[0.0631284  0.23039523 0.7314638 ]
