In [3]:
import numpy as np
arr1 = np.array([1,4,2,5,3])#creating numpy array
print(arr1)
arr2 = np.array([1,2,3,4], dtype = float) #explicitly mentioning the data type of resulting array
print(arr2)
arr3 = np.array([list(range(i, i+3)) for i in [2,4,6]])#creating 2d arrays
print(arr3)

[1 4 2 5 3]
[1. 2. 3. 4.]
[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [5]:
import numpy as np
arr0 = np.zeros(10, dtype = int)
print(arr0)
arr1 = np.ones((3,5), dtype = float)
print(arr1)
arr_of_choice = np.full((3,5), 3.14)
print(arr_of_choice)
arr_seq = np.arange(0, 20, 2)
print(arr_seq)
arr_random1 = np.random.random((3,3))
print(arr_random1)
arr_random2 = np.random.randint(0,10,(3,3))
print(arr_random2)
arr_identity = np.eye(3)
arr_empty = np.empty(3)
print(arr_empty)

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[ 0  2  4  6  8 10 12 14 16 18]
[[0.95779631 0.56307621 0.84396251]
 [0.6176366  0.65967916 0.57069545]
 [0.78789462 0.24881073 0.90054092]]
[[1 1 5]
 [5 2 2]
 [9 7 0]]
[3. 2. 1.]


In [7]:
#Accessing Numpy arrays
np.random.seed(0)
x1 = np.random.randint(4, 10, size = 6)
print(x1)
print(x1[-1])
x2 = np.random.randint(10, size =(3,4))
print(x2)
print(x2[2,-1])

[8 9 4 7 7 7]
7
[[7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
6


In [9]:
#Slicing in numpy arrays
np.random.seed(3)
x = np.arange(10)
print(x[5:], x[:5], x[5::-2])
x2 = np.random.randint(10, size =(3,4))
print(x2[:3, :2],x2[:3, ::2]) #2 rows, 3 cols  and all rows, alternate cols
print(x2[::-1, ::-1]) #reversing 2d array
print(x2[0]) #accessing 1st row
#can also be written as x2[0, :]
print(x2[:, 0]) #accessing 1st column

#numpy slices are views not a copy like lists in python
x2_sub = x2[:2, :2]
print(x2_sub)
x2[0,0] = 99
print(x2)
 #using .copy() to create shallow copies
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy[0, 0] = 55
print(x2)

[5 6 7 8 9] [0 1 2 3 4] [5 3 1]
[[8 9]
 [8 0]
 [9 9]] [[8 3]
 [8 5]
 [9 5]]
[[7 5 9 9]
 [3 5 0 8]
 [8 3 9 8]]
[8 9 3 8]
[8 8 9]
[[8 9]
 [8 0]]
[[99  9  3  8]
 [ 8  0  5  3]
 [ 9  9  5  7]]
[[99  9  3  8]
 [ 8  0  5  3]
 [ 9  9  5  7]]


In [11]:
#reshaping of arrays
# x = np.arange(1,10).reshape(3,3)
# print(x)

#concatenation of 1d arrays
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.concatenate([x,y])
z = np.concatenate([x,y,z])
print(z)
#concatenation of 2d arrays
grid = np.array([[1,2,3],[4,5,6]])
p = np.concatenate([grid, grid], axis = 0)
q = np.concatenate([grid,grid], axis = 1)
print(p)
print(q)
print(z)
grid = np.array([[9,8,7],[6,5,4]])
a = np.vstack([x,grid])
print(a)
b = np.array([[99],[99]])
b = np.hstack([grid,b])
print(b)

[1 2 3 3 2 1 1 2 3 3 2 1]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[1 2 3 3 2 1 1 2 3 3 2 1]
[[1 2 3]
 [9 8 7]
 [6 5 4]]
[[ 9  8  7 99]
 [ 6  5  4 99]]


In [17]:
#splitting of arrays
#splitting of arrays
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)
grid = np.arange(16).reshape(4,4)
upper, lower = np.vsplit(grid, [2])
print(upper,lower)
left, right = np.hsplit(grid, [2])
print(left, right)

[1 2 3] [99 99] [3 2 1]
[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [25]:
# Array Arithmetic

x = np.arange(4)
print(-x, x + 5, x - 2, x * 2, x / 2, x // 2, x ** 0.5, x % 2)
print(-(0.5 * x + 1) ** 2)
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

[ 0 -1 -2 -3] [5 6 7 8] [-2 -1  0  1] [0 2 4 6] [0.  0.5 1.  1.5] [0 0 1 1] [0.         1.         1.41421356 1.73205081] [0 1 0 1]
[-1.   -2.25 -4.   -6.25]
[2 1 0 1 2]
